include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    [build/**, "*.freezed.dart", "*.g.dart", "**/*.g.dart", "**/*.freezed.dart"]
  errors:
    use_if_null_to_convert_nulls_to_bools: ignore
    invalid_annotation_target: ignore
    avoid_final_parameters: ignore
    inference_failure_on_collection_literal: ignore
    unused_element: ignore
    avoid_catches_without_on_clauses: ignore



linter:
  rules:
    prefer_const_constructors: true
    public_member_api_docs: false
    lines_longer_than_80_chars: false
    one_member_abstracts: false
    omit_local_variable_types: false
    avoid_print: true
    prefer_single_quotes: true
    avoid_positional_boolean_parameters: false
    require_trailing_commas: true


bloc:
  rules:
    - avoid_public_bloc_methods
    - avoid_public_fields
