targets:
  $default:
    builders:
      dart_mappable_builder:
        options:
          caseStyle: snakeCase
          renameMethods:
            fromJson: fromJsonString
            toJson: toJsonString
            fromMap: fromJson
            toMap: toJson
