// ignore_for_file: public_member_api_docs,constant_identifier_names,type=lint,unused_element,unused_field
import 'package:flutter/foundation.dart';

//
// GENERATED CODE - DO NOT MODIFY BY HAND
// **************************************************************************
// Generated by flutter-assets-generator extension for VS Code
// @mrasityilmaz
// **************************************************************************

@immutable
final class Assets {
  Assets._();
  static final _Bottom_nav_bar_icons bottom_nav_bar_icons = _Bottom_nav_bar_icons._();
  static final _Fonts fonts = _Fonts._();
  static final _Icons icons = _Icons._();
  static final _Splash splash = _Splash._();


}

@immutable
final class _Bottom_nav_bar_icons {
  _Bottom_nav_bar_icons._();

  final String home_icon_svg = 'assets/bottom_nav_bar_icons/home_icon.svg';
  final String profile_icon_svg = 'assets/bottom_nav_bar_icons/profile_icon.svg';

}

@immutable
final class _Fonts {
  _Fonts._();

  final String euclid_circular_a_bold_ttf = 'assets/fonts/Euclid_Circular_A_Bold.ttf';
  final String euclid_circular_a_bold_italic_ttf = 'assets/fonts/Euclid_Circular_A_Bold_Italic.ttf';
  final String euclid_circular_a_italic_ttf = 'assets/fonts/Euclid_Circular_A_Italic.ttf';
  final String euclid_circular_a_light_ttf = 'assets/fonts/Euclid_Circular_A_Light.ttf';
  final String euclid_circular_a_light_italic_ttf = 'assets/fonts/Euclid_Circular_A_Light_Italic.ttf';
  final String euclid_circular_a_medium_ttf = 'assets/fonts/Euclid_Circular_A_Medium.ttf';
  final String euclid_circular_a_medium_italic_ttf = 'assets/fonts/Euclid_Circular_A_Medium_Italic.ttf';
  final String euclid_circular_a_regular_ttf = 'assets/fonts/Euclid_Circular_A_Regular.ttf';
  final String euclid_circular_a_semibold_ttf = 'assets/fonts/Euclid_Circular_A_SemiBold.ttf';
  final String euclid_circular_a_semibold_italic_ttf = 'assets/fonts/Euclid_Circular_A_SemiBold_Italic.ttf';

}

@immutable
final class _Icons {
  _Icons._();

  final String apple_icon_svg = 'assets/icons/apple_icon.svg';
  final String bonus_feature_icon_png = 'assets/icons/bonus_feature_icon.png';
  final String bonus_gem_icon_png = 'assets/icons/bonus_gem_icon.png';
  final String bonus_hearth_icon_png = 'assets/icons/bonus_hearth_icon.png';
  final String bonus_hearths_icon_png = 'assets/icons/bonus_hearths_icon.png';
  final String email_icon_svg = 'assets/icons/email_icon.svg';
  final String facebook_icon_svg = 'assets/icons/facebook_icon.svg';
  final String gem_icon_svg = 'assets/icons/gem_icon.svg';
  final String google_icon_svg = 'assets/icons/google_icon.svg';
  final String hide_icon_svg = 'assets/icons/hide_icon.svg';
  final String name_surname_icon_svg = 'assets/icons/name_surname_icon.svg';
  final String password_icon_svg = 'assets/icons/password_icon.svg';
  final String plus_icon_svg = 'assets/icons/plus_icon.svg';

}

@immutable
final class _Splash {
  _Splash._();

  final String n1152_icon_png = 'assets/splash/1152_icon.png';
  final String n600_icon_png = 'assets/splash/600_icon.png';

}

